# Generated by Django 5.0.1 on 2024-02-06 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='figuras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('saga', models.CharField(max_length=50)),
                ('precio', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='juegos',
            name='precio',
            field=models.IntegerField(default=0),
        ),
    ]
