# Generated by Django 5.0.1 on 2024-02-06 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion1', '0002_figuras_juegos_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='figuras',
            name='precio',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='juegos',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
