# Generated by Django 5.0.1 on 2024-02-07 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion1', '0003_alter_figuras_precio_alter_juegos_precio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentarios',
            options={'verbose_name': 'Comentario', 'verbose_name_plural': 'Comentarios'},
        ),
        migrations.AlterModelOptions(
            name='figuras',
            options={'ordering': ['saga'], 'verbose_name': 'figura', 'verbose_name_plural': 'figuras'},
        ),
        migrations.AlterModelOptions(
            name='juegos',
            options={'ordering': ['nombre'], 'verbose_name': 'juego', 'verbose_name_plural': 'juegos'},
        ),
        migrations.AlterModelOptions(
            name='usuarios',
            options={'ordering': ['nombre'], 'verbose_name': 'usuario', 'verbose_name_plural': 'usuarios'},
        ),
        migrations.AlterModelOptions(
            name='vendedores',
            options={'ordering': ['numeroV'], 'verbose_name': 'vendedor', 'verbose_name_plural': 'vendedores'},
        ),
        migrations.AddField(
            model_name='usuarios',
            name='contrasena',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
