# Generated by Django 5.0.1 on 2024-02-07 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion1', '0004_alter_comentarios_options_alter_figuras_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='contrasena',
        ),
    ]
